---
format: html
toc: true
---

# Chapter 18  {-}

## Sections 18.1 - 18.5 (Atoms/Moles/Temperature/Thermal Expansion) {-}
1. What is the meaning of atomic mass number ($A$)?
2. The atomic mass number for Nitrogen is 14.  What is the mass of one Nitrogen atom?
3. What is Avogadro's number and what is significant about this number?
4. What is number density and what is the mathematical equation to calculate it?
5. How do you calculate the number of moles of a substance?
6. How do you convert from degrees Fahrenheit to degrees Celsius?
7. How do you convert from degrees Celsius to Kelvins?
8. What is the lowest possible temperature (absolute zero) in Kelvins, degrees Celsius and degrees Fahrenheit?
9. What is the equation for linear thermal expansion? Explain the meaning of all of the variables.
10. What is the equation for volume thermal expansion? Explain the meaning of all of the variables.
11. Where is the record of Samuel, the Lamanite?

## Section 18.6 - 18.7 (Ideal Gases) {-}
1. What is a phase diagram?
2. What is the critical point on a phase diagram?
3. What is the triple point on a phase diagram?
4. What are the conditions for a gas to be considered and "ideal" gas?
5. Write down the ideal gas law and explain what each variable means.  (There are two versions of this equation.. explain both.)
6. What is the value of the universal gas constant ($R$)?
7. What is the value of Boltzmann's constant ($k_B$)?
8. What is meant by an isochoric process?
9. What is meant by an isobaric process?
10. What is meant by an isothermal process?
11. Recite Isaiah 55:8-9
