---
format: html
toc: true
---

# Chapter 33  {-}

## Sections 33.1 - 33.2 (Light Interference) {-}
1. What is the mathematical condition for **constructive** interference of light?
2. What is the mathematical condition for **destructive** interference of light?
3. Explain Young's double slit experiment and the significance of the results?
4. What is the mathematical expression for the location of bright spots in a double slit experiment?
5. If the wavelength of light shining on a double slit **increases**, the spacing between bright spots __________? (increases/decreases)
6. Recite John 17:3

## Section 33.3 - 33.8 (Diffraction Gratings/ Single and Mutliple Slits) {-}
1. What is a diffraction grating?
2. What is the mathematical expression for the location of **bright** spots produced by a **diffraction grating**?
3. What is a reflection grating?
4. What is Huygen's principle?
5. What is the mathematical expression for the location of **dark** spots produced by a **single slit**?
6. Describe the Michelson Interferometer.
7. Recite 2 Nephi 2:27
