---
format: html
toc: true
---

# Chapter 14  {-}

## Sections 14.1 - 14.3 (Fluids) {-}

1. Explain how a suction cup works.
2. Explain why gases exert pressure.
3. Explain why liquids exert pressure.
4. What are the SI units of density?
5. What are the SI units of pressure?
6. What is a barometer?  Explain how it works.
7. Some liquid is placed in a pipe that is bent into the shape of a "U".  If you draw a horizontal line that connects one side of the u-tube to the other, how does the fluid pressure on one side compare to the other side? How do you know?
8. What is atmospheric pressure on Earth?
9. What is Pascal's principle?
10. What is the density of air at standard temperature and pressure (STP)?
11. What is the density of water at standard temperature and pressure (STP)?
12. What is the difference between gauge and absolute pressure?
13. What is the mathematical definition of (equation for) pressure?
14. What is the mathematical equation for the pressure at depth  $h$ in a fluid?
15. Where can you find the Savior's sermon on the mount? (It's found in more than one place.)


## Section 14.4 (Buoyancy) {-}

1. While at the beach, you push a beach ball under the surface of the water and notice that it is quite hard to keep submerged.  What is exerting an upward force on the ball. (Don't just say buoyant force!!)
2. What determines whether an object floats or sinks when placed in a fluid?
3. Two blocks are identical in size. One is made of lead and sits on the bottom of a pond; the other is made of wood and floats on top.  Upon which block is the buoyant force greater? Explain.
4. What is Archimedes' principle?
5. Two objects are floating in water.  Half of object #1 is submerged in the water and 75\% of object #2 is submerged.  Which object is more dense? Can you prove it mathematically?
6. (T/F)  The buoyant force on a submerged object depends on both its size and shape?
7. Recite Helaman 5:12.



## Section 14.5 (Fluid Dynamics) {-}

1. A fluid is flowing through a pipe that has a narrow section and a wider section. Why does the speed of the fluid increase in the narrow section and decrease in the wider section of the pipe?
2. What is the equation for volume flow rate? (related question: What are the SI units of volume flow rate?)
3. What is the mathematical formula for Bernoulli's equation?
4. A pipe starts at the bottom of a hill and continues until it reaches the top.  The pipe is wide at the bottom and narrow at the top.  Compare the pressure and flow speed at the top and bottom.
5. Draw a Venturi tube and explain how it works.
6. Use Bernoulli's principle (equation) to explain how an airplane wing (airfoil) generates lift.
7. Where is the parable

## Section 14.6 (Elasticity) {-}

1. What is the mathematical equation and SI units for tensile stress?
2. What is the mathematical equation and SI units for volume stress?
3. What is the mathematical equation and SI units for linear strain?
4. What is the mathematical equation and SI units for volume strain?
5. What is Young's modulus and what are its SI units?
6. What is Bulk modulus and what are its SI units?
